[environment]
; production,development,test
current = development


[logger_path_development]
log_dir = C:\Users\User\Desktop\SLT\Incident Monitor GIT
[logger_path_testing]
log_dir = C:\Users\User\Desktop\SLT\Incident Monitor GIT
[logger_path_production]
log_dir = C:\Users\User\Desktop\SLT\Incident Monitor GIT

[server_host_port_development]
host = 127.0.0.1
port = 8000
[server_host_port_testing]
host = 127.0.0.1
port = 8080
[server_host_port_production]
host = 0.0.0.0
port = 7183


[api_urls_development]
EMAIL_API_URL = http://127.0.0.1:8000/api/email/send-emails

[api_urls_testing]
EMAIL_API_URL = http://127.0.0.1:8080/api/email/send-emails

[api_urls_production]
EMAIL_API_URL = http://127.0.0.1:7183/api/email/send-emails


